### Site Settings ###
title               : Matthis Le Texier
description         : >-
                       Welcome ! I'm Matthis Le Texier,

                       game developer since 2020 
                       and here is my portfolio.
baseurl             : "/Portfolio/"                   # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : "matthisl/matthisl.github.io"   # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)
remote_theme        : yousinix/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/blog.html
  # - pages/projects/random-synapse.md
  # - pages/projects/vyder.md


### Author Info ###
author:
  name              : Matthis Le Texier
  # image             : https://i.imgur.com/uyDNQnn.jpg
  # behance           : your_username
# dribbble          : your_username
  email             : matthis.letexier@gmail.com
  # facebook          : your_username
  github            : MatthisLT
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : matthis-le-texier
  # medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  # twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: MLT-Portofolio                       # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
